name: install-test
on:
  push:
  pull_request:

jobs:
  wheel-install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Build wheel
        run: |
          python -m pip install --upgrade pip build
          python -m build --wheel .

      - name: Install wheel in fresh venv
        run: |
          python -m venv /tmp/venv
          /tmp/venv/bin/pip install dist/*.whl
          /tmp/venv/bin/python - <<'PY'
          import importlib, sys, pathlib
          pkg = "aoc"
          importlib.import_module(pkg)
          print(f"{pkg} import OK on", sys.version)
          PY
